// src/components/Sections/header.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const Yscroll = ref(0);
const header = ref(null);


const handleScroll = () => {
  Yscroll.value = window.scrollY;
  
  if (Yscroll.value > 80) {
    header.value.style.position = 'fixed';
    header.value.classList.add ('gradient-box');
  }
  else{
    header.value.style.position = 'relative';
    header.value.classList.remove ('gradient-box');
  }
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});
</script>





<template>

    <header ref="header">
        <div class="logo"></div>
        <div class="menu">
          <ul>
            <li>Produtos</li>
            <li>Sobre</li>
            <li>Parceiros</li>
            <li>Localização</li>
            <li>Contato</li>
          </ul>
        </div>

    </header>


</template>




<style>

header{
    margin: auto;
    width: 1270px;
    position: relative;
    display: flex;
    justify-content: space-between;
    padding: 1.5rem;
    box-sizing: border-box;
    align-items: center;
    background-color: transparent;
    
    top: 0;
    

    .logo {
      background-image: url("/src/assets/logo-SF.png"); 
      background-position: center;
      background-repeat: no-repeat;
      background-size: contain; 
      height: 80px;
      width: 120px;
    }


    .menu{
      ul{
        display: flex;
        gap: 3rem;
        
        li {
          cursor: pointer;
          color: white;
          font-weight: 400;
          font-size: 1.5rem;

        }

        li:hover{
          text-decoration: underline;
          
        }

      }

    }


  }


  /*------------Especific styles----------------------------------------- */

  .gradient-box {
  background: linear-gradient(to right, white, #0cc0df);
  }

</style>

// src/components/header.jsx
import styled from "styled-components";
import logo from "../assets/logo-SF.png"
import intro_bg from "../assets/background.png"


const Intro_bg = styled.div`
    background-image: url(${intro_bg});
    background-size: cover;
    background-position: center;
    width: 1270px;
    margin: auto;
    overflow: hidden;
    
    
    header{
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 100%;
        height: 4.375rem;
        padding: 1rem;
        box-sizing: border-box;

        ul{ 
            display: flex;
            justify-content: space-between;
            gap: 1rem;

            li{
                cursor:pointer;
                color: white;
            }

            li:hover{
                text-decoration: underline;
            }
        }
    }
    
    section{
        width: 1270px;
        height: 100vh;
    }

`

const __logo = styled.div`
    background-image: url(${logo});
    background-size: cover;
    background-position: center;
    color: blue;
    width: 100px;
    height: 70px;
`

export default function Header() {

    return (
        <Intro_bg>
            <header>
                <__logo></__logo>
                <ul>
                    <li>Serviços</li>
                    <li>Sobre nós</li>
                    <li>Clientes</li>
                    <li>Fale Conosco</li>
                    <li>Localização</li>
                </ul>
            </header>
            <section></section>
        </Intro_bg>


    )

}
